#!/bin/bash
#  ## Script Realizado por Carlos A Salazar <csalazart33@gmail.com>
#  ## Si deseas Contribuir puedes hacer un FORK y contribuir al respecto
#  ## En Github https://github.com/csalazart/SF2ShortsCommands 

echo "ejecutando..."
echo "console $@"
php app/console $@

echo "Actualizando Permisos.."
chmod 775 * -Rf
chmod 777 app/cache -Rf
chmod 777 app/logs -Rf


