#!/bin/bash

### Script Realizado por Carlos A Salazar <csalazart33@gmail.com>
### Si deseas Contribuir puedes hacer un FORK y contribuir al respecto
### En Github https://github.com/csalazart/SF2ShortsCommands 

echo "ejecutando..."
echo "console $@"
php bin/console $@